concurrent = 4
[[runners]]
  name = "Kubernetes Runner"
  url = "https://gitlab.com/"
  token = "GR1348941TFgP5DRDsbQjSAnyGmo6"
  executor = "docker"
  [runners.docker]
  tls_verify = true
  image = "ubuntu:20.04"
  privileged = false
  disable_entrypoint_overwrite = false
  oom_kill_disable = false
  disable_cache = false
  volumes = [
  "/cache",
]
  shm_size = 0
  allowed_pull_policies = ["always", "if-not-present"]
  allowed_images = ["my.registry.tld:5000/*:*"]
  allowed_services = ["my.registry.tld:5000/*:*"]
  [runners.docker.volume_driver_ops]
  "size" = "50G"