image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  KUBECONFIG: /etc/deploy/kubeconfig.yaml

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  script:
    - apk add --update ca-certificates openssl curl tar gzip bash
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - echo $KUBECONFIG_FILE > $KUBECONFIG
    - kubectl config use-context my-eks-cluster
    - kubectl set image deployment/my-app my-app=$CI_REGISTRY_IMAGE:latest
  environment:
    name: production
  only:
    - master
